try:
    a = 10
finally:
    raise Exception('Error!')
    #print('hello')
